* Authclient sample client

This project contains boilerplate code for using the [[https://github.com/steinarb/authservice][authservice pluggable user administration service]] (based on [[https://shiro.apache.org][apache shiro]])in a web application using the [[https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.http.whiteboard.html][OSGi web whiteboard]], running in [[https://karaf.apache.org][apache karaf]].

** Development Status
[[https://github.com/steinarb/authservice-sampleclient/actions/workflows/authservice-sampleclient-maven-ci-build.yml][file:https://github.com/steinarb/authservice-sampleclient/actions/workflows/authservice-sampleclient-maven-ci-build.yml/badge.svg]]
[[https://coveralls.io/github/badges/shields?branch=master][file:https://coveralls.io/repos/github/badges/shields/badge.svg?branch=master]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice-sampleclient&metric=alert_status#.svg]]

[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/images/project_badges/sonarcloud-white.svg]]

[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice-sampleclient&metric=sqale_index#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice-sampleclient&metric=coverage#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice-sampleclient&metric=ncloc#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice-sampleclient&metric=code_smells#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice-sampleclient&metric=sqale_rating#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice-sampleclient&metric=security_rating#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice-sampleclient&metric=bugs#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice-sampleclient&metric=vulnerabilities#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice-sampleclient&metric=duplicated_lines_density#.svg]]
[[https://sonarcloud.io/summary/new_code?id=steinarb_authservice-sampleclient][file:https://sonarcloud.io/api/project_badges/measure?project=steinarb_authservice-sampleclient&metric=reliability_rating#.svg]]

** Try this code

To verify that this code will run in you karaf instance:
 1. Clone and build this project:
    #+BEGIN_EXAMPLE
      git clone https://github.com/steinarb/authservice-sampleclient
      cd authservice-sampleclient
      mvn clean install
    #+END_EXAMPLE
 2. from the karaf console, install the authservice prerequisite
    #+BEGIN_EXAMPLE
      feature:repo-add mvn:no.priv.bang.authservice/karaf/LATEST/xml/features
      feature:install user-admin-with-testdb
    #+END_EXAMPLE
 3. From the karaf console install the authservice sample client project
    #+BEGIN_EXAMPLE
      feature:repo-add mvn:no.priv.bang.authservice/authservice.sampleclient/LATEST/xml/features
      feature:install authservice-sampleclient
    #+END_EXAMPLE
 4. Open the URL http://localhost:8181/sampleauthserviceclient in a web browser
 5. In the login page that opens, log in with username admin and password admin
 6. Try visiting the "Admin page (requires the useradmin role)" link and verify that it allowed
 7. Click on the "Back to the top" link
 8. Click on the "Log out (will redirect to the login page)" link (which will redirect to the login page)
 9. Log in with username jad and password 1ad
 10. Verify that this user does not have access to the admin page

** Adapt this project to your project

This procedure assumes that your webapp project is a multimodule maven build.

 1. Clone this project, remove the .git directory from the clone
 2. Move the cloned project to the level of the modules in your multimodule build
 3. Change the POM to fit in:
    1. Change the groupId to match your project
    2. Change the artifactId to match the groupId (maven-bundle-plugin is happiest when the last segment of the groupId matches the first part of the artifactId.  The bundle name and the default package will become groupId+artifactId but with only a single copy of the last part of groupId and first part of the artifactId)
    3. (Not strictly necessary) Make your parent POM be the parent of the project
    4. (If you set a parent) Remove the <version>
 4. Add the new module to <modules> in your top POM
 5. Change the HTTP_WHITEBOARD_CONTEXT_PATH in AuthserviceSampleClientServletContextHelper to what your webapp's context path to be
 6. change the src/main/resource/shiro.ini to limit access to sub-paths of your webapp (e.g. by using pairs of roles and paths like the configuration for the /admin path)
 7. (Not strictly necessary but more aesthetically pleasing) change the HTTP_WHITEBOARD_CONTEXT_NAME to something more appropriate to the path, and change all other usages (in this project AuthserviceSampleClientShiroFilter and AuthserviceSampleClientServlet)

You can change the name of the classes to be more appropriate, but that doesn't have any other effect than aesthetics.  No classes are exported from the bundle.

** License
The license of this karaf feature, is Apache Public License v 2.0

See the LICENSE file for details.
